#!/usr/bin/env bash

#   CAAIS, a bash script to install or remove Chaotic-AUR.
#   Copyright (C) 2022 RaptaG
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.

# Definitions
ver="2.3-dev.1"
fname="$(basename $0)"
appendInPacmanConf="$(grep 'chaotic-aur' /etc/pacman.conf)"
isArchBased="$(grep 'ID_LIKE=arch' /etc/os-release | awk -F 'ID_LIKE=' '{print $2}')"
isException="$(grep 'ID=' /etc/os-release | awk -F 'ID=' '{print $2}')"
foreignChaoticAURpacks="$(pacman -Qm | awk '{print $1}')"

function startup() {
     echo "CAAIS, version ${ver}"
     echo "Current operation: ${action} Chaotic-AUR"
}

function rootCheck() {
     if [ "${EUID}" -ne 0 ]; then
          echo "Error: Root permissions are required for ${fname} to work."
          echo "Please run './${fname}' for more information."
          exit 1
     fi
}

function installCheck() {
     if [ "$(find /etc/pacman.d/ -name chaotic-mirrorlist)" == "/etc/pacman.d/chaotic-mirrorlist" ]; then
          isInstalled="true"
     else
          isInstalled="false"
     fi
}

# Check if the distro is (based on) Arch Linux
case ${isException} in
arch | artix)
     sleep 0s
     ;;
*)
     if [ "${isArchBased}" != "arch" ]; then
          echo "Error: Your system is not (based on) Arch Linux. Chaotic-AUR cannot be installed."
          exit 1
     fi
     ;;
esac

# Download & install Chaotic-AUR
function install() {
     startup

     installCheck
     if [ "${isInstalled}" != "false" ]; then
          echo -e "\nError: Chaotic-AUR is already installed."
          exit 1
     fi

     # Key
     echo "Installing the key..."
     pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com > /dev/null 2>&1
     pacman-key --lsign-key FBA220DFC880C036 > /dev/null 2>&1

     # Keyring & mirrorlist
     echo "Downloading the keyring..."
     pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm > /dev/null 2>&1

     echo "Downloading the mirrorlist..."
     pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm > /dev/null 2>&1

     # Append in pacman.conf
     if [ "${appendInPacmanConf}" != "[chaotic-aur]" ]; then
          echo "Appending Chaotic-AUR in pacman.conf..."
          echo -e "\r\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
     fi

     # Refresh mirrorlists
     echo "Refreshing the mirrorlists..."
     pacman -Sy > /dev/null 2>&1

     # Finish
     echo "Chaotic-AUR has been successfully installed!"
     exit 0
}

# Uninstall Chaotic-AUR
function remove() {     
     startup
     installCheck
     if [ "${isInstalled}" != "true" ]; then
          echo -e "\nError: Chaotic-AUR is already uninstalled."
          exit 1
     fi

     # Key
     echo "Deleting the key..."
     pacman-key --delete 3FFA0B5E092ED4095E26F69B8ADB4AEC585061CF > /dev/null 2>&1

     # Keyring & mirrorlist
     echo "Uninstalling the keyring..."
     pacman -Rns chaotic-keyring --noconfirm > /dev/null 2>&1

     echo "Uninstalling the mirrorlist..."
     pacman -Rns chaotic-mirrorlist --noconfirm > /dev/null 2>&1

     # Remove from pacman.conf
     echo "Removing Chaotic-AUR from pacman.conf..."
     sed -i '/chaotic-aur/d' /etc/pacman.conf
     sed -i '/chaotic-mirrorlist/d' /etc/pacman.conf

     # Refresh mirrorlists
     echo "Refreshing the mirrorlists..."
     pacman -Sy > /dev/null 2>&1

     # AUR convertion
     echo -n "Do you wish to reinstall your old Chaotic-AUR packages from AUR? [Y/n] "
     read answer

     case "${answer}" in
     [nN])
          echo "Chaotic-AUR has been successfully removed!"
          exit 0
          ;;
     *)
          unset answer
          ;;
     esac

     echo "Reinstalling..."
     pacman -Rns ${foreignChaoticAURpacks} --noconfirm > /dev/null 2>&1
     pamac build ${foreignChaoticAURpacks} --no-confirm > /dev/null 2>&1

     # Finish 
     echo "Chaotic-AUR has been successfully removed and all your Chaotic-AUR packages have been reinstalled!"
     exit 0
}

# Find the option selected and run the correct command
case "$1" in
-h | help | "")
     echo "Usage: ${fname} [OPTION]"
     echo
     echo "-h, --help                        This help menu"
     echo
     echo "-a, --about                       Display informaton about CAAIS"
     echo
     echo "-i, --install                     Download and install Chaotic-AUR"
     echo
     echo "-r, --remove                      Remove Chaotic-AUR from your system"
     echo
     echo "You can access the GithUb repo for help and information here:"
     echo "https://github.com/RaptaG/CAAIS"
     exit 0
     ;;
-a | about)
     echo "Version of CAAIS currently used: ${ver}"
     echo "GitHub release: https://github.com/RaptaG/CAAIS/releases/tag/${ver}"
     echo
     echo "Current contributors:"
     echo "1) RaptaG (Main developer)"
     echo "2) terminalmaid (Pull Request #1)"
     echo "3) TruncatedDinosour (Pull Request #2)"
     echo
     echo
     echo "CAAIS, Copyright (C) 2022 RaptaG"
     echo "This program comes with ABSOLUTELY NO WARRANTY; for details see <https://www.gnu.org/licenses/>"
     echo "This is free software, and you are welcome to redistribute it"
     echo "under certain conditions; See <https://www.gnu.org/licenses/> for details."
     exit 0
     ;;
-i | install)
     rootCheck
     action="Install"
     install
     ;;
-r | remove)
     rootCheck
     action="Remove"
     remove
     ;;
*)
     echo "Invalid option '$1'. Please run './${fname}' to see the list of all the options availiable."
     exit 1
     ;;
esac
